
CREATE TABLE IF NOT EXISTS auth_test(
	id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    login VARCHAR(15) NOT NULL,
    email VARCHAR(40) NOT NULL,
    phone VARCHAR(30) NOT NULL,
    pwd  VARCHAR(250) NOT NULL
    
);





